### ISSUE TITLE
a way to organize downloads into folder heirarchy

### ISSUE THREAD

**Issue by samirsd** [RubenArtmann/bandcamp-dl#1]
like if you enter a record label link it would download like so: 
./downloaded/${label}/artists/${artist}/albums/{$album}/tracks/{$track}

**Comment by RubenArtmann** [comment]
Thanks for the feedback.
Should be added, please close the issue if it works.
See readme.md for information on how to upgrade

**Comment by samirsd** [comment]
very cool, thanks! it works most of the time but I did find it errors out on this bandcamp for example: 

http://maggie5.bandcamp.com

error: Uncaught TypeError: Cannot read property 'slice' of undefined
			let array = hash.slice(1).split("#");
			                 ^
    at mod.ts:52:21


perhaps it has to do with unplayable files.

**Comment by RubenArtmann** [comment]
please open a new issue

**Comment by RubenArtmann** [comment]
should be fixed though (upgrade)
