### ISSUE TITLE
Brew and Deno how to run ?

### ISSUE THREAD

**Issue by benhuma** [RubenArtmann/bandcamp-dl#6]
Hi there,
it's not an issue but how do i run your script when i've already have brew bandcamp-dl ? 
Can't figure it out.
Sorry to bother.

**Comment by RubenArtmann** [comment]
Hope you already figured it out yourself(since two months passed), but ```brew bandcamp-dl``` is different from this script (their github is https://github.com/iheanyi/bandcamp-dl)

if for some reason you still want to use this script, ```brew install deno``` followed by ```deno run --allow-net --allow-read --allow-write --no-check https://raw.githubusercontent.com/RubenArtmann/bandcamp-dl/main/mod.ts <bandcamp_url>``` should get the job done.
